version: "3"
services:
  front:
    build: ./projects/go-todo-client/
    command: yarn start
    volumes:
      - ./projects/go-todo-client/:/myapp/frontend
    ports:
      - "3000:3000"
  back:
    build:
      context: ./projects/go-todo-api/
      target: builder
    command: air
    volumes:
      - ./projects/go-todo-api/:/myapp/backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CORS_ORIGIN=http://localhost:3000
