version: "3"
services:
  front:
    build: ./projects/go-todo-client/
    command: yarn start
    volumes:
      - ./projects/go-todo-client/:/myapp/frontend
    ports:
      - "3000:3000"
  back:
    build:
      context: ./projects/go-todo-api/
      target: builder
    command: air
    volumes:
      - ./projects/go-todo-api/:/myapp/backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - postgres
  postgres:
    build: db
    volumes:
      - postgresql-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go-todo-api-db
volumes:
  postgresql-data:
